version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build

    steps:
      - checkout
      - run:
          name:    Setup
          command: stack setup
      - run:
          name:    Install
          command: stack install
      - run:
          name:    Test
          command: stack test
